services:
  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 9229:9229 #debuging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    environment: 
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 3000      
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
